### PR TITLE
Adding Unread Messages Reader

### PR DESCRIPTION
**Pull request by PrajvalRaval**

### CODE REVIEW

**Review by Sing-Li — CHANGES_REQUESTED** [review]
Can we have a mode where the "sender's name" of the messages in a channel is also voiced?

In additional, perhaps an "envelope" mode, like voicemail, where you read off the date it was sent, and the number of attachments that the message has.    Probably no need to read off the attachment at this time.

If you do this, please make it a "mode" that can be switched on/off, because often we'll want ONLY THE TEXT of the message read.    Once we get anonymous reader working.

**Comment by PrajvalRaval** [comment]
> Can we have a mode where the "sender's name" of the messages in a channel is also voiced?
> 
> In additional, perhaps an "envelope" mode, like voicemail, where you read off the date it was sent, and the number of attachments that the message has. Probably no need to read off the attachment at this time.
> 
> If you do this, please make it a "mode" that can be switched on/off, because often we'll want ONLY THE TEXT of the message read. Once we get anonymous reader working.

Sender's Username Is Already Being Voiced.

**Review by acerbisgianluca — CHANGES_REQUESTED** [review]
Code seems work, but I think it would be better to use `let` instead of `var` and `const` when possible to maintain integrity. Also you can use `===` instead of `==` and `foreach` (you can still get the index) instead of a simple for loop. Sorry but I'm reading Clean Code right now 😂

**Comment by PrajvalRaval** [comment]
> > Can we have a mode where the "sender's name" of the messages in a channel is also voiced?
> > In additional, perhaps an "envelope" mode, like voicemail, where you read off the date it was sent, and the number of attachments that the message has. Probably no need to read off the attachment at this time.
> > If you do this, please make it a "mode" that can be switched on/off, because often we'll want ONLY THE TEXT of the message read. Once we get anonymous reader working.
> 
> Sender's Username Is Already Being Voiced.

Envelope Mode will require to create a different intent as this intent simply returns a single string of messages and will not be possible to get information.

**Comment by PrajvalRaval** [comment]
> Code seems work, but I think it would be better to use `let` instead of `var` and `const` when possible to maintain integrity. Also you can use `===` instead of `==` and `foreach` (you can still get the index) instead of a simple for loop. Sorry but I'm reading Clean Code right now 😂

Don't think quite necessary right now , but thanks for the suggestion anyway

**Review by Sing-Li — APPROVED** [review]

**Pull request merged**
