### PR TITLE
Adding Portuguese Language And Fixed Unread Intent

### PR DESCRIPTION
**Pull request by PrajvalRaval**
This PR is done upon @TheDreamSaver PR so it will not interfere with merging it. Added Portuguese language support and fixed GetUnreads intent which was not functioning after adding Jargon.

### CODE REVIEW

**Review by acerbisgianluca — CHANGES_REQUESTED** [review]
New sample utterance structure seems ok!
Btw you should update skill.json adding new language blocks (3 example phrases, skill name and description)

**Comment by PrajvalRaval** [comment]
> New sample utterance structure seems ok!
> Btw you should update skill.json adding new language blocks (3 example phrases, skill name and description)

Changed skill.json file as per your suggestion, please make sure it is correct. Thanks

**Comment by acerbisgianluca** [comment]
> > New sample utterance structure seems ok!
> > Btw you should update skill.json adding new language blocks (3 example phrases, skill name and description)
> 
> Changed skill.json file as per your suggestion, please make sure it is correct. Thanks

Yep, it's okay.

**Comment by Sing-Li** [comment]
Pls resolve the minor conflicts.

**Pull request merged**
