### PR TITLE
Adding 10 More Locales To Alexa Skill

### PR DESCRIPTION
**Pull request by PrajvalRaval**
This PR add's 10 more locales that open gates for developers worldwide to create their own Rocket Chat Alexa Skill in their own language. After merge of this PR we will have 12/14 locales implemented leaving Italian and Japanese for Development.

### CODE REVIEW

**Comment by TheDreamSaver** [comment]
My suggestion is that we should wait for subject matter experts to review the specific models as well as responses first before merging in our codebase.

As the end results of using some translate service instead can be something which might not be the natural way to say it in that specific language.

I've experienced such a scenario before with a German Skill I worked on and I used google translate for converting the English responses and utterances but it failed badly when we did the beta testing and then had to get a German native speaker to help us correct various nuances.

Also, it isn't stopping us from moving forward with the other core features, so I will suggest waiting for review from language experts before we add this to our codebase.

**Comment by PrajvalRaval** [comment]
> My suggestion is that we should wait for subject matter experts to review the specific models as well as responses first before merging in our codebase.
> 
> As the end results of using some translate service instead can be something which might not be the natural way to say it in that specific language.
> 
> I've experienced such a scenario before with a German Skill I worked on and I used google translate for converting the English responses and utterances but it failed badly when we did the beta testing and then had to get a German native speaker to help us correct various nuances.
> 
> Also, it isn't stopping us from moving forward with the other core features, so I will suggest waiting for review from language experts before we add this to our codebase.

I definitely agree that using a translator service cannot always provide an accurate result and should use a native speaker for sample utterances but I also think that you will agree with the point that as a developer it is our duty to make it simpler for new contributors to contribute. If a non-english speaker has to contribute their language to us they would have to create this models anyway, and since we have models already created they will have to fix only the Utterance Sentences and Words to a more suitable ones as per their language and don't have to dabble with whole codebase and structures in order to do that, which will be beneficial for both them and us. We ourselves can work on only English, Portuguese and Italian models since we have people who can contribute to it and let other models just be there as a beginner task for new contributors coming from the non-english countries alexa supports. Since we are not publishing this skill in those models anytime soon. Hope you get the point.👍

**Review by acerbisgianluca — APPROVED** [review]
It seems all okay. BTW I agree with you, we are just putting the bases for new contributors

**Comment by TheDreamSaver** [comment]
I see your point. It's completely valid and I agree with it.
As a precaution though, you should just add a few issues for those non-english models, something like (review requested from subject expert for German).

And I think we are good to go with the merge @Sing-Li

**Comment by PrajvalRaval** [comment]
> I see your point. It's completely valid and I agree with it.
> As a precaution though, you should just add a few issues for those non-english models, something like (review requested from subject expert for German).
> 
> And I think we are good to go with the merge @Sing-Li

@TheDreamSaver @acerbisgianluca Thanks for agreeing with me on this one and I definitely invite you to post an issue of concerns that you have.

**Comment by acerbisgianluca** [comment]
> As a precaution though, you should just add a few issues for those non-english models, something like (review requested from subject expert for German).

Yes, we should add new labels to tag beginner issues

**Review by TheDreamSaver — APPROVED** [review]

**Comment by Sing-Li** [comment]
@PrajvalRaval please resolve the simple conflicts and I will merge at once.  Thx

**Comment by PrajvalRaval** [comment]
> @PrajvalRaval please resolve the simple conflicts and I will merge at once. Thx

@Sing-Li Solved

**Pull request merged**
